# --------------------------------------
# Kubernetes Ingress for Flask App
# Purpose: Expose Flask application via Ingress
# Target: Local development using Kubernetes
# ---------------------------------------

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-app-service
                # Dev note: This routes traffic to the service's port 80.
                port:
                  number: 80
