# --------------------------------------
# Kubernetes Service for Flask App
# Purpose: Expose Flask application within the cluster
# Target: Local development using Kubernetes
# ---------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  # Dev note: makes the service only reachable from within the cluster.
  type: ClusterIP
  selector:
    app: flask-app
  ports:
    - protocol: TCP

      port: 80
      targetPort: 5000
